0.1

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -3,8 +3,19 @@
 
 if [ "$#" -lt 3 ]; then
 	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-elif [ "$#" -lt 4 ]; then
-	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
+	exit 1
+fi
+
+path_to_file=$1
+ip=$2
+username=$3
+path_to_key=$4
+
+scp -o "StrictHostKeyChecking no" -i "$path_to_key" "$path_to_file" "$username@$ip:~/"
+
+if [ $? -eq 0 ]
+then
+  echo "FILE TRANSFER WAS SUCCESSFULL"
 else
-	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
+  echo "FILE TRANSFER FAILED"
 fi
